//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScnEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScnEdit.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ColumnHeader {
            get {
                return ResourceManager.GetString("ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        internal static string ColumnSymbol {
            get {
                return ResourceManager.GetString("ColumnSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment.
        /// </summary>
        internal static string FragmentHeader {
            get {
                return ResourceManager.GetString("FragmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string InsertSymbol {
            get {
                return ResourceManager.GetString("InsertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string LineHeader {
            get {
                return ResourceManager.GetString("LineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines.
        /// </summary>
        internal static string LinesUnit {
            get {
                return ResourceManager.GetString("LinesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        internal static string LineSymbol {
            get {
                return ResourceManager.GetString("LineSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading includes....
        /// </summary>
        internal static string LoadingIncludes {
            get {
                return ResourceManager.GetString("LoadingIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize in progress....
        /// </summary>
        internal static string NormalizeInProgress {
            get {
                return ResourceManager.GetString("NormalizeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was too large to apply syntax highlighting correctly..
        /// </summary>
        internal static string OutOfMemoryException {
            get {
                return ResourceManager.GetString("OutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PathHeader {
            get {
                return ResourceManager.GetString("PathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing tracks....
        /// </summary>
        internal static string ProcessingTracks {
            get {
                return ResourceManager.GetString("ProcessingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready1 {
            get {
                return ResourceManager.GetString("Ready1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace results.
        /// </summary>
        internal static string ReplaceResults {
            get {
                return ResourceManager.GetString("ReplaceResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        internal static string ReplaceSymbol {
            get {
                return ResourceManager.GetString("ReplaceSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing in project files....
        /// </summary>
        internal static string Replacing {
            get {
                return ResourceManager.GetString("Replacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery.
        /// </summary>
        internal static string Scenery {
            get {
                return ResourceManager.GetString("Scenery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in project files....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sel.
        /// </summary>
        internal static string SelectionSymbol {
            get {
                return ResourceManager.GetString("SelectionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; was changed,
        ///do you wish to save it first?.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
    }
}
