//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScnSyntax.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Keywords : global::System.Configuration.ApplicationSettingsBase {
        
        private static Keywords defaultInstance = ((Keywords)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Keywords())));
        
        public static Keywords Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>addvalues</string>\r\n  <string>animation</string>\r\n  <string>atmo</string>\r" +
            "\n  <string>camera</string>\r\n  <string>condition</string>\r\n  <string>config</stri" +
            "ng>\r\n  <string>copyvalues</string>\r\n  <string>description</string>\r\n  <string>dy" +
            "namic</string>\r\n  <string>else</string>\r\n  <string>end[a-z]*</string>\r\n  <string" +
            ">event</string>\r\n  <string>event0</string>\r\n  <string>event1</string>\r\n  <string" +
            ">event2</string>\r\n  <string>eventall0</string>\r\n  <string>eventall1</string>\r\n  " +
            "<string>eventall2</string>\r\n  <string>eventlauncher</string>\r\n  <string>FirstIni" +
            "t</string>\r\n  <string>getvalues</string>\r\n  <string>include</string>\r\n  <string>" +
            "light</string>\r\n  <string>lights</string>\r\n  <string>line_loop</string>\r\n  <stri" +
            "ng>line_strip</string>\r\n  <string>lines</string>\r\n  <string>material</string>\r\n " +
            " <string>memcell</string>\r\n  <string>memcompare</string>\r\n  <string>model</strin" +
            "g>\r\n  <string>multiple</string>\r\n  <string>node</string>\r\n  <string>origin</stri" +
            "ng>\r\n  <string>propability</string>\r\n  <string>putvalues</string>\r\n  <string>rot" +
            "ate</string>\r\n  <string>setvalues</string>\r\n  <string>sky</string>\r\n  <string>so" +
            "und</string>\r\n  <string>test</string>\r\n  <string>time</string>\r\n  <string>track<" +
            "/string>\r\n  <string>traction</string>\r\n  <string>trainset</string>\r\n  <string>tr" +
            "iangle_fan</string>\r\n  <string>triangle_strip</string>\r\n  <string>triangles</str" +
            "ing>\r\n  <string>updatevalues</string>\r\n  <string>velocity</string>\r\n</ArrayOfStr" +
            "ing>")]
        public global::System.Collections.Specialized.StringCollection Set1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Set1"]));
            }
            set {
                this["Set1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SetVelocity</string>
  <string>ShuntVelocity</string>
  <string>PassengerStopPoint</string>
  <string>FoulingPoint</string>
  <string>SetProximityVelocity</string>
  <string>OutsideStation</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Set2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Set2"]));
            }
            set {
                this["Set2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Wait_for_orders</string>
  <string>Prepare_engine</string>
  <string>Change_direction</string>
  <string>Obey_train</string>
  <string>Shunt</string>
  <string>WarningSignal</string>
  <string>CabSignal</string>
  <string>Jump_to_order</string>
  <string>Jump_to_first_order</string>
  <string>Timetable</string>
  <string>Emergency_brake</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Set3 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Set3"]));
            }
            set {
                this["Set3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ambient</string>
  <string>canyon</string>
  <string>conductor</string>
  <string>connected</string>
  <string>cross</string>
  <string>diffuse</string>
  <string>flat</string>
  <string>headdriver</string>
  <string>mountains</string>
  <string>nobody</string>
  <string>normal</string>
  <string>passenger</string>
  <string>passengers</string>
  <string>reardriver</string>
  <string>river</string>
  <string>road</string>
  <string>specular</string>
  <string>switch</string>
  <string>tunnel</string>
  <string>unvis</string>
  <string>vis</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Set4 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Set4"]));
            }
            set {
                this["Set4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>none</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Set5 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Set5"]));
            }
            set {
                this["Set5"] = value;
            }
        }
    }
}
