//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScnEdit.StyleSchemes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Styles_Default : global::System.Configuration.ApplicationSettingsBase {
        
        private static Styles_Default defaultInstance = ((Styles_Default)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Styles_Default())));
        
        public static Styles_Default Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Identifier {
            get {
                return ((global::System.Drawing.FontStyle)(this["Identifier"]));
            }
            set {
                this["Identifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Comment {
            get {
                return ((global::System.Drawing.FontStyle)(this["Comment"]));
            }
            set {
                this["Comment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle Keyword {
            get {
                return ((global::System.Drawing.FontStyle)(this["Keyword"]));
            }
            set {
                this["Keyword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Keyword1 {
            get {
                return ((global::System.Drawing.FontStyle)(this["Keyword1"]));
            }
            set {
                this["Keyword1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Keyword2 {
            get {
                return ((global::System.Drawing.FontStyle)(this["Keyword2"]));
            }
            set {
                this["Keyword2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Keyword3 {
            get {
                return ((global::System.Drawing.FontStyle)(this["Keyword3"]));
            }
            set {
                this["Keyword3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Keyword4 {
            get {
                return ((global::System.Drawing.FontStyle)(this["Keyword4"]));
            }
            set {
                this["Keyword4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Underline")]
        public global::System.Drawing.FontStyle Path {
            get {
                return ((global::System.Drawing.FontStyle)(this["Path"]));
            }
            set {
                this["Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Number {
            get {
                return ((global::System.Drawing.FontStyle)(this["Number"]));
            }
            set {
                this["Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle Time {
            get {
                return ((global::System.Drawing.FontStyle)(this["Time"]));
            }
            set {
                this["Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle Command {
            get {
                return ((global::System.Drawing.FontStyle)(this["Command"]));
            }
            set {
                this["Command"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle Special {
            get {
                return ((global::System.Drawing.FontStyle)(this["Special"]));
            }
            set {
                this["Special"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Underline")]
        public global::System.Drawing.FontStyle SameWord {
            get {
                return ((global::System.Drawing.FontStyle)(this["SameWord"]));
            }
            set {
                this["SameWord"] = value;
            }
        }
    }
}
